spring.application.name=order-service

# Server
server.port=${SERVER_PORT:8082}

# H2 + JPA
spring.datasource.url=jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Product Service URL (Order -> Product call)
product.service.url=${PRODUCT_SERVICE_URL:http://product-service:8081}

# Actuator (needed for Docker healthchecks)
management.endpoints.web.exposure.include=health,info

# Unleash config
unleash.app-name=order-service
unleash.instance-id=${HOSTNAME:local}
#unleash.api-url=http://localhost:4242/api
unleash.api-url=${UNLEASH_API_URL:http://unleash-server:4242/api}
unleash.api-token=${UNLEASH_API_TOKEN:default-token}
