spring.application.name=product-service

# Server
server.port=${SERVER_PORT:8081}

# H2 + JPA
spring.datasource.url=jdbc:h2:mem:products;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# H2 console (helpful for demo/debug)
spring.h2.console.enabled=true

# Actuator (needed for Docker healthchecks)
management.endpoints.web.exposure.include=health,info

# Unleash config
unleash.app-name=product-service
unleash.instance-id=${HOSTNAME:local}
#unleash.api-url=http://localhost:4242/api
unleash.api-url=${UNLEASH_API_URL:http://unleash-server:4242/api}
unleash.api-token=${UNLEASH_API_TOKEN:default:development.default-token}